[phases.setup]
nixPkgs = ["...", "nodejs", "chromium", "google-chrome-stable"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
# මෙතැන අගය පසුවට භාවිතා කිරීමට
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"